ordererorg_domain: "aais.thetech.digital"
domain: "analytics.thetech.digital"
internal_domain: "analytics.internal.thetech.digital"
node_type: "analytics"
network:
  org_name: "analytics"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: "carrier"
      domain: "carrier.thetech.digital"
  channels:
  - name: "defaultchannel"
    chaincode:
      name: "openidl-cc-default"
      repo_url: "github.com/rajeshsanjeevi/openidl-main.git"
      repo_branch: "hig-carrier"
      repo_path: "openidl-chaincode/chaincode/openidl"
  - name: anal-aais
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_aais_pdc"
          policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
  - name: anal-carr
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_carr_pdc"
          policy: "OR('analyticsMSP.member', 'carrierMSP.member')"
