{{ if .Values.chaincode.usecollectionconfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: commit-chaincode-{{ $.Values.channel.name }}-collection-config-{{ $.Values.chaincode.version }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: commit-chaincode-{{ $.Values.channel.name }}-collection-config-{{ $.Values.chaincode.version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
data:
  collection.config.base64: {{ .Values.chaincode.collectionconfig | quote }}
{{ end }}

