---
- name: Update kubeconfig and set context to openidl {{ app_cluster_name }}
  shell: |
    export AWS_PROFILE=cicd-role; aws eks update-kubeconfig --region {{ aws_region }} --name {{ app_cluster_name }}

- name: Create a openidl k8s namespace
  community.kubernetes.k8s:
    name: openidl
    api_version: v1
    kind: Namespace
    state: present

- name: Download git repository content
  git:
    repo: "https://{{ gitrepo_username|urlencode() }}:{{ gitrepo_password|urlencode() }}@{{ gitrepo_name }}"
    dest: /tmp/openidl
    force: yes
    single_branch: yes
    version: "{{ gitrepo_branch }}"


- name: Deploy openIDL app on AAIS node using helm
  shell: |
    helm upgrade --recreate-pods --install {{ env }}-{{ org_name }} /tmp/openidl/openidl-k8s -f /tmp/openidl/openidl-k8s/global-values-{{ env }}-{{ org_name }}.yaml \
      -n openidl --set global.datacallapp.ingressenabled=true --set global.utilities.ingressenabled=true \
      --set global.ui.ingressenabled=true --set global.insurancedatamanager.ingressenabled=true \
      --set global.secrets.install=false
  when: org_name == "aais"

- name: Deploy openIDL app on Analytics node using helm
  shell: |
    helm upgrade --recreate-pods --install {{ env }}-{{ org_name }} /tmp/openidl/openidl-k8s -f /tmp/openidl/openidl-k8s/global-values-{{ env }}-{{ org_name }}.yaml \
      -n openidl --set global.datacallapp.ingressenabled=true --set global.utilities.ingressenabled=true \
      --set global.ui.ingressenabled=true --set global.secrets.install=false
  when: org_name == "anal"

- name: Deploy openIDL app on Carrier node using helm
  shell: |
    helm upgrade --recreate-pods --install {{ env }}-{{ org_name }} /tmp/openidl/openidl-k8s -f /tmp/openidl/openidl-k8s/global-values-{{ env }}-{{ org_name }}.yaml \
      -n openidl --set global.datacallapp.ingressenabled=true --set global.utilities.ingressenabled=true \
      --set global.carrierui.ingressenabled=true --set global.insurancedatamanager.ingressenabled=true \
      --set global.secrets.install=false
  when: (org_name != "aais") and (org_name != "anal")

- name: Dispose temporary git repository content
  file:
    path: /tmp/openidl/
    state: absent
